apiVersion: v1
kind: Pod
metadata:
  name: ex7-pod
spec:
  initContainers:
    - name: output-1
      image: nginx
      command: ['sh','-c','wget https://adtech.cyberagent.io/ > /usr/share/nginx/html/inde.html']
      volumeMounts:
      - name: html-volume
        mountPath: /usr/share/nginx/html/
  containers:
    - name: nginx-container
      image: nginx:1.12
      volumeMounts:
      - name: html-volume
        mountPath: /usr/share/nginx/html/
  volumes:
  - name: html-volume
    : 
