version: "3"
services:
  app:
    build:
      context: ./Dockerfiles/php
    ports:
      - ${PHP_PORT}:80
    volumes:
      - ${PROJECT_PATH}:/var/www/html
  db:
    build: ./Dockerfiles/mysql/.
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - ./Docker/mysql/data:/var/lib/mysql
